
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Produtos from "./produtos/page";
import "./globals.css";
import Cadastro from "./cadastro/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cadastro></Cadastro>
        <Produtos/>
      </body>
    </html>
  );
}
