
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Produtos from "./produtos/page";
import "./globals.css";
import Cadastro from "./cadastro/page";
import HomePage from "./home/page";
import Login from "./login/page";
import Acessibilidade from "./acessibilidade/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomePage></HomePage>
        <Acessibilidade></Acessibilidade>
        <Cadastro></Cadastro>
        <Login></Login>
        <Produtos/>
      </body>
    </html>
  );
}
